-- 1. Create Profiles table (linked to Supabase Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    fullname TEXT NOT NULL,
    email TEXT NOT NULL,
    role TEXT CHECK (role IN ('buyer', 'seller', 'both')) DEFAULT 'buyer',
    faculty TEXT DEFAULT 'Unknown',
    avatar_url TEXT,
    is_verified BOOLEAN DEFAULT FALSE,
    status TEXT DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Categories table
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    icon TEXT,
    count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Products table
CREATE TABLE IF NOT EXISTS public.products (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    price BIGINT NOT NULL,
    description TEXT,
    image TEXT NOT NULL,
    images TEXT[] DEFAULT '{}',
    category TEXT REFERENCES public.categories(slug),
    seller_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    rating DECIMAL DEFAULT 0,
    reviews INTEGER DEFAULT 0,
    condition TEXT CHECK (condition IN ('New', 'Like New', 'Used')),
    location TEXT,
    negotiable BOOLEAN DEFAULT FALSE,
    delivery TEXT[] DEFAULT '{}',
    status TEXT DEFAULT 'available',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create Orders table
CREATE TABLE IF NOT EXISTS public.orders (
    id TEXT PRIMARY KEY, -- e.g. ORD-2025-001
    buyer_id UUID REFERENCES public.profiles(id),
    product_id UUID REFERENCES public.products(id),
    amount BIGINT NOT NULL,
    status TEXT CHECK (status IN ('Pending', 'Processing', 'Delivered', 'Cancelled')) DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Create Wishlist table
CREATE TABLE IF NOT EXISTS public.wishlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    product_id UUID REFERENCES public.products(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, product_id)
);

-- 6. Create Market Stats table
CREATE TABLE IF NOT EXISTS public.market_stats (
    id INTEGER PRIMARY KEY DEFAULT 1,
    total_listings INTEGER DEFAULT 0,
    total_sellers INTEGER DEFAULT 0,
    total_transactions INTEGER DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Create FAQs table
CREATE TABLE IF NOT EXISTS public.faqs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    q TEXT NOT NULL,
    a TEXT NOT NULL,
    order_index INTEGER DEFAULT 0
);

-- 8. Create Testimonials table
CREATE TABLE IF NOT EXISTS public.testimonials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    text TEXT NOT NULL,
    avatar TEXT
);

-- Trigger to create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, fullname, email, role, faculty)
  VALUES (
    new.id, 
    COALESCE(new.raw_user_meta_data->>'fullname', 'Student'), 
    new.email, 
    COALESCE(new.raw_user_meta_data->>'role', 'buyer'),
    COALESCE(new.raw_user_meta_data->>'faculty', 'Unknown')
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Default Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles
  FOR SELECT USING (true);

CREATE POLICY "Users can update their own profiles." ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Products are viewable by everyone." ON public.products
  FOR SELECT USING (true);

CREATE POLICY "Sellers can manage their own products." ON public.products
  FOR ALL USING (auth.uid() = seller_id);

-- Initial Data Seed
INSERT INTO public.categories (name, slug, icon) VALUES
('Textbooks', 'textbooks', '📚'),
('Food & Drinks', 'food', '🍱'),
('Electronics', 'electronics', '💻'),
('Fashion', 'fashion', '👕'),
('Services', 'services', '🛠️');

INSERT INTO public.market_stats (id, total_listings, total_sellers, total_transactions)
VALUES (1, 150, 45, 1200)
ON CONFLICT (id) DO NOTHING;
